#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_MAIN                                101
#define IDD_ABOUT                               110
#define IDD_ANIME_INFO                          111
#define IDD_ANIME_INFO_PAGE01                   112
#define IDD_ANIME_INFO_PAGE02                   113
#define IDD_ANIME_LIST                          114
#define IDD_FEED_CONDITION                      115
#define IDD_FEED_FILTER                         116
#define IDD_FEED_FILTER_PAGE1                   117
#define IDD_FEED_FILTER_PAGE2                   118
#define IDD_FEED_FILTER_PAGE3                   119
#define IDD_FORMAT                              120
#define IDD_HISTORY                             121
#define IDD_INPUT                               122
#define IDD_MAIN                                123
#define IDD_SEARCH                              124
#define IDD_SEASON                              125
#define IDD_SETTINGS                            126
#define IDD_SETTINGS_APP_BEHAVIOR               127
#define IDD_SETTINGS_APP_CONNECTION             128
#define IDD_SETTINGS_APP_INTERFACE              129
#define IDD_SETTINGS_APP_LIST                   130
#define IDD_SETTINGS_LIBRARY_CACHE              131
#define IDD_SETTINGS_LIBRARY_FOLDERS            132
#define IDD_SETTINGS_RECOGNITION_GENERAL        133
#define IDD_SETTINGS_RECOGNITION_MEDIA          134
#define IDD_SETTINGS_RECOGNITION_STREAM         135
#define IDD_SETTINGS_SERVICES_MAL               136
#define IDD_SETTINGS_SHARING_HTTP               137
#define IDD_SETTINGS_SHARING_MESSENGER          138
#define IDD_SETTINGS_SHARING_MIRC               139
#define IDD_SETTINGS_SHARING_SKYPE              140
#define IDD_SETTINGS_SHARING_TWITTER            141
#define IDD_SETTINGS_TORRENTS_DISCOVERY         142
#define IDD_SETTINGS_TORRENTS_DOWNLOADS         143
#define IDD_SETTINGS_TORRENTS_FILTERS           144
#define IDD_STATS                               145
#define IDD_TEST_RECOGNITION                    146
#define IDD_TORRENT                             147
#define IDD_UPDATE                              148
#define IDD_UPDATE_NEW                          149
#define IDC_BUTTON_ADDFOLDER                    1000
#define IDC_BUTTON_BROWSE                       1001
#define IDC_BUTTON_CACHE_CLEAR                  1002
#define IDC_BUTTON_CANCELSEARCH                 1003
#define IDC_BUTTON_FORMAT_BALLOON               1004
#define IDC_BUTTON_FORMAT_HTTP                  1005
#define IDC_BUTTON_FORMAT_MIRC                  1006
#define IDC_BUTTON_FORMAT_MSN                   1007
#define IDC_BUTTON_FORMAT_SKYPE                 1008
#define IDC_BUTTON_FORMAT_TWITTER               1009
#define IDC_BUTTON_MIRC_TEST                    1010
#define IDC_BUTTON_REMOVEFOLDER                 1011
#define IDC_BUTTON_TORRENT_BROWSE_APP           1012
#define IDC_BUTTON_TORRENT_BROWSE_FOLDER        1013
#define IDC_BUTTON_TWITTER_AUTH                 1014
#define IDC_CHECK_ANIME_ALT                     1015
#define IDC_CHECK_ANIME_REWATCH                 1016
#define IDC_CHECK_AUTOSTART                     1017
#define IDC_CHECK_CACHE1                        1018
#define IDC_CHECK_CACHE2                        1019
#define IDC_CHECK_CACHE3                        1020
#define IDC_CHECK_FOLDERS_WATCH                 1021
#define IDC_CHECK_GENERAL_CLOSE                 1022
#define IDC_CHECK_GENERAL_MINIMIZE              1023
#define IDC_CHECK_HIGHLIGHT                     1024
#define IDC_CHECK_HTTP                          1025
#define IDC_CHECK_LIST_ENGLISH                  1026
#define IDC_CHECK_LIST_PROGRESS_AIRED           1027
#define IDC_CHECK_LIST_PROGRESS_AVAILABLE       1028
#define IDC_CHECK_MESSENGER                     1029
#define IDC_CHECK_MIRC                          1030
#define IDC_CHECK_MIRC_ACTION                   1031
#define IDC_CHECK_MIRC_MULTISERVER              1032
#define IDC_CHECK_NOTIFY_NOTRECOGNIZED          1033
#define IDC_CHECK_NOTIFY_RECOGNIZED             1034
#define IDC_CHECK_SKYPE                         1035
#define IDC_CHECK_START_CHECKEPS                1036
#define IDC_CHECK_START_LOGIN                   1037
#define IDC_CHECK_START_MINIMIZE                1038
#define IDC_CHECK_START_VERSION                 1039
#define IDC_CHECK_TORRENT_AUTOCHECK             1040
#define IDC_CHECK_TORRENT_AUTOCREATEFOLDER      1041
#define IDC_CHECK_TORRENT_AUTOSETFOLDER         1042
#define IDC_CHECK_TORRENT_AUTOUSEFOLDER         1043
#define IDC_CHECK_TORRENT_FILTER                1044
#define IDC_CHECK_TWITTER                       1045
#define IDC_CHECK_UPDATE_CHECKMP                1046
#define IDC_CHECK_UPDATE_CONFIRM                1047
#define IDC_CHECK_UPDATE_GOTO                   1048
#define IDC_CHECK_UPDATE_RANGE                  1049
#define IDC_CHECK_UPDATE_ROOT                   1050
#define IDC_CHECK_UPDATE_WAITMP                 1051
#define IDC_COMBO_ANIME_SCORE                   1052
#define IDC_COMBO_ANIME_STATUS                  1053
#define IDC_COMBO_DBLCLICK                      1054
#define IDC_COMBO_FEED_ELEMENT                  1055
#define IDC_COMBO_FEED_FILTER_ACTION            1056
#define IDC_COMBO_FEED_FILTER_MATCH             1057
#define IDC_COMBO_FEED_FILTER_OPTION            1058
#define IDC_COMBO_FEED_OPERATOR                 1059
#define IDC_COMBO_FEED_VALUE                    1060
#define IDC_COMBO_MDLCLICK                      1061
#define IDC_COMBO_THEME                         1062
#define IDC_COMBO_TORRENT_FOLDER                1063
#define IDC_COMBO_TORRENT_SEARCH                1064
#define IDC_COMBO_TORRENT_SOURCE                1065
#define IDC_DATETIME_FINISH                     1066
#define IDC_DATETIME_START                      1067
#define IDC_EDIT_ANIME_ALT                      1068
#define IDC_EDIT_ANIME_FOLDER                   1069
#define IDC_EDIT_ANIME_PROGRESS                 1070
#define IDC_EDIT_ANIME_SYNOPSIS                 1071
#define IDC_EDIT_ANIME_TAGS                     1072
#define IDC_EDIT_ANIME_TITLE                    1073
#define IDC_EDIT_DELAY                          1074
#define IDC_EDIT_EXTERNALLINKS                  1075
#define IDC_EDIT_FEED_NAME                      1076
#define IDC_EDIT_HTTP_URL                       1077
#define IDC_EDIT_INPUT                          1078
#define IDC_EDIT_MIRC_CHANNELS                  1079
#define IDC_EDIT_MIRC_SERVICE                   1080
#define IDC_EDIT_PASS                           1081
#define IDC_EDIT_PREVIEW                        1082
#define IDC_EDIT_PROXY_HOST                     1083
#define IDC_EDIT_PROXY_PASS                     1084
#define IDC_EDIT_PROXY_USER                     1085
#define IDC_EDIT_SEARCH                         1086
#define IDC_EDIT_TORRENT_APP                    1087
#define IDC_EDIT_TORRENT_INTERVAL               1088
#define IDC_EDIT_USER                           1089
#define IDC_LINK_ANIME_FANSUB                   1090
#define IDC_LINK_DEFAULTS                       1091
#define IDC_LINK_MAL                            1092
#define IDC_LINK_NOWPLAYING                     1093
#define IDC_LINK_THEMES                         1094
#define IDC_LINK_TWITTER                        1095
#define IDC_LIST_EVENT                          1096
#define IDC_LIST_FEED_FILTER_ANIME              1097
#define IDC_LIST_FEED_FILTER_CONDITIONS         1098
#define IDC_LIST_FEED_FILTER_PRESETS            1099
#define IDC_LIST_FOLDERS_ROOT                   1100
#define IDC_LIST_MAIN                           1101
#define IDC_LIST_MEDIA                          1102
#define IDC_LIST_SEARCH                         1103
#define IDC_LIST_SEASON                         1104
#define IDC_LIST_STREAM_PROVIDER                1105
#define IDC_LIST_TEST_RECOGNITION               1106
#define IDC_LIST_TORRENT                        1107
#define IDC_LIST_TORRENT_FILTER                 1108
#define IDC_PROGRESS_UPDATE                     1109
#define IDC_RADIO_MIRC_CHANNEL1                 1110
#define IDC_RADIO_MIRC_CHANNEL2                 1111
#define IDC_RADIO_MIRC_CHANNEL3                 1112
#define IDC_RADIO_TORRENT_APP1                  1113
#define IDC_RADIO_TORRENT_APP2                  1114
#define IDC_RADIO_TORRENT_NEW1                  1115
#define IDC_RADIO_TORRENT_NEW2                  1116
#define IDC_REBAR_MAIN                          1117
#define IDC_REBAR_SEASON                        1118
#define IDC_REBAR_TORRENT                       1119
#define IDC_RICHEDIT_ABOUT                      1120
#define IDC_RICHEDIT_FORMAT                     1121
#define IDC_RICHEDIT_UPDATE                     1122
#define IDC_SPIN_DELAY                          1123
#define IDC_SPIN_INPUT                          1124
#define IDC_SPIN_PROGRESS                       1125
#define IDC_SPIN_TORRENT_INTERVAL               1126
#define IDC_STATIC_ANIME_DETAILS                1127
#define IDC_STATIC_ANIME_IMG                    1128
#define IDC_STATIC_ANIME_STAT1                  1129
#define IDC_STATIC_ANIME_STAT2                  1130
#define IDC_STATIC_ANIME_STAT3                  1131
#define IDC_STATIC_ANIME_STAT4                  1132
#define IDC_STATIC_CACHE1                       1133
#define IDC_STATIC_CACHE2                       1134
#define IDC_STATIC_CACHE3                       1135
#define IDC_STATIC_FEED_FILTER_DISCARDTYPE      1136
#define IDC_STATIC_FEED_FILTER_LIMIT            1137
#define IDC_STATIC_HEADER                       1138
#define IDC_STATIC_HEADER1                      1139
#define IDC_STATIC_HEADER2                      1140
#define IDC_STATIC_HEADER3                      1141
#define IDC_STATIC_HEADER4                      1142
#define IDC_STATIC_INPUTINFO                    1143
#define IDC_STATIC_TITLE                        1144
#define IDC_STATIC_UPDATE_DETAILS               1145
#define IDC_STATIC_UPDATE_PROGRESS              1146
#define IDC_STATIC_UPDATE_TITLE                 1147
#define IDC_STATUSBAR_MAIN                      1148
#define IDC_TAB_ANIME                           1149
#define IDC_TAB_MAIN                            1150
#define IDC_TAB_PAGES                           1151
#define IDC_TOOLBAR_FEED_FILTER                 1152
#define IDC_TOOLBAR_MAIN                        1153
#define IDC_TOOLBAR_MENU                        1154
#define IDC_TOOLBAR_SEARCH                      1155
#define IDC_TOOLBAR_SEASON                      1156
#define IDC_TOOLBAR_TORRENT                     1157
#define IDC_TREE_MAIN                           1158
#define IDC_TREE_SECTIONS                       1159
#define IDS_KEYWORD_AUDIO                       40000
#define IDS_KEYWORD_EXTENSION                   40001
#define IDS_KEYWORD_EXTRA                       40002
#define IDS_KEYWORD_EXTRA_UNSAFE                40003
#define IDS_KEYWORD_VERSION                     40004
#define IDS_KEYWORD_VIDEO                       40005
#define IDS_KEYWORD_EPISODE                     40006
#define IDS_KEYWORD_EPISODE_PREFIX              40007
