#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_MAIN                                101
#define IDD_ABOUT                               110
#define IDD_ABOUT_TAIGA                         111
#define IDD_ANIME_INFO                          112
#define IDD_ANIME_INFO_PAGE01                   113
#define IDD_ANIME_INFO_PAGE02                   114
#define IDD_EVENT                               115
#define IDD_FEED_CONDITION                      116
#define IDD_FEED_FILTER                         117
#define IDD_FEED_FILTER_PAGE1                   118
#define IDD_FEED_FILTER_PAGE2                   119
#define IDD_FEED_FILTER_PAGE3                   120
#define IDD_FILTER                              121
#define IDD_FORMAT                              122
#define IDD_INPUT                               123
#define IDD_MAIN                                124
#define IDD_SEARCH                              125
#define IDD_SETTINGS                            126
#define IDD_SETTINGS_PAGE01                     127
#define IDD_SETTINGS_PAGE02                     128
#define IDD_SETTINGS_PAGE03                     129
#define IDD_SETTINGS_PAGE04                     130
#define IDD_SETTINGS_PAGE05                     131
#define IDD_SETTINGS_PAGE06                     132
#define IDD_SETTINGS_PAGE07                     133
#define IDD_SETTINGS_PAGE08                     134
#define IDD_SETTINGS_PAGE09                     135
#define IDD_SETTINGS_PAGE10                     136
#define IDD_SETTINGS_PAGE11                     137
#define IDD_SETTINGS_PAGE12                     138
#define IDD_SETTINGS_PAGE13                     139
#define IDD_SETTINGS_PAGE14                     140
#define IDD_SETTINGS_PAGE15                     141
#define IDD_TEST_RECOGNITION                    142
#define IDD_TORRENT                             143
#define IDD_UPDATE                              144
#define IDC_BUTTON_ADDFOLDER                    1000
#define IDC_BUTTON_CANCELSEARCH                 1001
#define IDC_BUTTON_EVENT_CLEAR                  1002
#define IDC_BUTTON_FILTERLIST                   1003
#define IDC_BUTTON_FORMAT_BALLOON               1004
#define IDC_BUTTON_FORMAT_HTTP                  1005
#define IDC_BUTTON_FORMAT_MIRC                  1006
#define IDC_BUTTON_FORMAT_MSN                   1007
#define IDC_BUTTON_FORMAT_SKYPE                 1008
#define IDC_BUTTON_FORMAT_TWITTER               1009
#define IDC_BUTTON_MIRC_TEST                    1010
#define IDC_BUTTON_REMOVEFOLDER                 1011
#define IDC_BUTTON_TORRENT_BROWSE               1012
#define IDC_BUTTON_TORRENT_FILTER_ADD           1013
#define IDC_BUTTON_TORRENT_FILTER_DELETE        1014
#define IDC_BUTTON_TWITTER_AUTH                 1015
#define IDC_CHECK_ANIME_REWATCH                 1016
#define IDC_CHECK_AUTOSTART                     1017
#define IDC_CHECK_BALLOON                       1018
#define IDC_CHECK_EXIT_ASK                      1019
#define IDC_CHECK_EXIT_SAVEBUFFER               1020
#define IDC_CHECK_FILTER_NEWEPS                 1021
#define IDC_CHECK_FILTER_STATUS1                1022
#define IDC_CHECK_FILTER_STATUS2                1023
#define IDC_CHECK_FILTER_STATUS3                1024
#define IDC_CHECK_FILTER_TYPE1                  1025
#define IDC_CHECK_FILTER_TYPE2                  1026
#define IDC_CHECK_FILTER_TYPE3                  1027
#define IDC_CHECK_FILTER_TYPE4                  1028
#define IDC_CHECK_FILTER_TYPE5                  1029
#define IDC_CHECK_FILTER_TYPE6                  1030
#define IDC_CHECK_FOLDERS_WATCH                 1031
#define IDC_CHECK_GENERAL_CLOSE                 1032
#define IDC_CHECK_GENERAL_MINIMIZE              1033
#define IDC_CHECK_HIGHLIGHT                     1034
#define IDC_CHECK_HTTP                          1035
#define IDC_CHECK_LIST_PROGRESS_EPS             1036
#define IDC_CHECK_MESSENGER                     1037
#define IDC_CHECK_MIRC                          1038
#define IDC_CHECK_MIRC_ACTION                   1039
#define IDC_CHECK_MIRC_MULTISERVER              1040
#define IDC_CHECK_SKYPE                         1041
#define IDC_CHECK_START_CHECKEPS                1042
#define IDC_CHECK_START_LOGIN                   1043
#define IDC_CHECK_START_MINIMIZE                1044
#define IDC_CHECK_START_VERSION                 1045
#define IDC_CHECK_TORRENT_AUTOCHECK             1046
#define IDC_CHECK_TORRENT_AUTOSETFOLDER         1047
#define IDC_CHECK_TORRENT_FILTER                1048
#define IDC_CHECK_TORRENT_HIDE                  1049
#define IDC_CHECK_TWITTER                       1050
#define IDC_CHECK_UPDATE_CHECKMP                1051
#define IDC_CHECK_UPDATE_RANGE                  1052
#define IDC_COMBO_ANIME_SCORE                   1053
#define IDC_COMBO_ANIME_STATUS                  1054
#define IDC_COMBO_DBLCLICK                      1055
#define IDC_COMBO_FEED_ELEMENT                  1056
#define IDC_COMBO_FEED_FILTER_ACTION            1057
#define IDC_COMBO_FEED_FILTER_MATCH             1058
#define IDC_COMBO_FEED_OPERATOR                 1059
#define IDC_COMBO_FEED_VALUE                    1060
#define IDC_COMBO_MDLCLICK                      1061
#define IDC_COMBO_THEME                         1062
#define IDC_COMBO_TORRENT_SOURCE                1063
#define IDC_DATETIME_FINISH                     1064
#define IDC_DATETIME_START                      1065
#define IDC_EDIT_ANIME_ALT                      1066
#define IDC_EDIT_ANIME_INFO                     1067
#define IDC_EDIT_ANIME_PROGRESS                 1068
#define IDC_EDIT_ANIME_TAGS                     1069
#define IDC_EDIT_ANIME_TITLE                    1070
#define IDC_EDIT_DELAY                          1071
#define IDC_EDIT_FEED_NAME                      1072
#define IDC_EDIT_HTTP_URL                       1073
#define IDC_EDIT_INPUT                          1074
#define IDC_EDIT_MIRC_CHANNELS                  1075
#define IDC_EDIT_MIRC_SERVICE                   1076
#define IDC_EDIT_PASS                           1077
#define IDC_EDIT_PREVIEW                        1078
#define IDC_EDIT_PROXY_HOST                     1079
#define IDC_EDIT_PROXY_PASS                     1080
#define IDC_EDIT_PROXY_USER                     1081
#define IDC_EDIT_SEARCH                         1082
#define IDC_EDIT_TORRENT_APP                    1083
#define IDC_EDIT_TORRENT_INTERVAL               1084
#define IDC_EDIT_USER                           1085
#define IDC_LINK_ABOUT                          1086
#define IDC_LINK_ANIME_FANSUB                   1087
#define IDC_LINK_MAL                            1088
#define IDC_LINK_TWITTER                        1089
#define IDC_LIST_EVENT                          1090
#define IDC_LIST_FEED_FILTER_ANIME              1091
#define IDC_LIST_FEED_FILTER_CONDITIONS         1092
#define IDC_LIST_FEED_FILTER_PRESETS            1093
#define IDC_LIST_FOLDERS_ANIME                  1094
#define IDC_LIST_FOLDERS_ROOT                   1095
#define IDC_LIST_MAIN                           1096
#define IDC_LIST_MEDIA                          1097
#define IDC_LIST_SEARCH                         1098
#define IDC_LIST_TEST_RECOGNITION               1099
#define IDC_LIST_TORRENT                        1100
#define IDC_LIST_TORRENT_FILTER                 1101
#define IDC_PROGRESS_UPDATE                     1102
#define IDC_RADIO_API1                          1103
#define IDC_RADIO_API2                          1104
#define IDC_RADIO_LIST_PROGRESS1                1105
#define IDC_RADIO_LIST_PROGRESS2                1106
#define IDC_RADIO_MIRC_CHANNEL1                 1107
#define IDC_RADIO_MIRC_CHANNEL2                 1108
#define IDC_RADIO_MIRC_CHANNEL3                 1109
#define IDC_RADIO_TORRENT_APP1                  1110
#define IDC_RADIO_TORRENT_APP2                  1111
#define IDC_RADIO_TORRENT_NEW1                  1112
#define IDC_RADIO_TORRENT_NEW2                  1113
#define IDC_RADIO_UPDATE_MODE1                  1114
#define IDC_RADIO_UPDATE_MODE2                  1115
#define IDC_RADIO_UPDATE_MODE3                  1116
#define IDC_RADIO_UPDATE_TIME1                  1117
#define IDC_RADIO_UPDATE_TIME2                  1118
#define IDC_RADIO_UPDATE_TIME3                  1119
#define IDC_REBAR_MAIN                          1120
#define IDC_REBAR_TORRENT                       1121
#define IDC_RICHEDIT_FORMAT                     1122
#define IDC_SPIN_DELAY                          1123
#define IDC_SPIN_INPUT                          1124
#define IDC_SPIN_PROGRESS                       1125
#define IDC_SPIN_TORRENT_INTERVAL               1126
#define IDC_STATIC_ABOUT_BUILD                  1127
#define IDC_STATIC_ABOUT_TITLE                  1128
#define IDC_STATIC_ABOUT_VERSION                1129
#define IDC_STATIC_ANIME_IMG                    1130
#define IDC_STATIC_ANIME_INFO1                  1131
#define IDC_STATIC_ANIME_INFO2                  1132
#define IDC_STATIC_ANIME_TITLE                  1133
#define IDC_STATIC_FEED_FILTER_LIMIT            1134
#define IDC_STATIC_HEADER                       1135
#define IDC_STATIC_HEADER1                      1136
#define IDC_STATIC_HEADER2                      1137
#define IDC_STATIC_HEADER3                      1138
#define IDC_STATIC_INPUTINFO                    1139
#define IDC_STATIC_TITLE                        1140
#define IDC_STATIC_UPDATE_PROGRESS              1141
#define IDC_STATUSBAR_MAIN                      1142
#define IDC_STATUSBAR_TORRENT                   1143
#define IDC_TAB_ABOUT                           1144
#define IDC_TAB_ANIME                           1145
#define IDC_TAB_MAIN                            1146
#define IDC_TOOLBAR_FEED_FILTER                 1147
#define IDC_TOOLBAR_MAIN                        1148
#define IDC_TOOLBAR_SEARCH                      1149
#define IDC_TOOLBAR_TORRENT                     1150
#define IDC_TREE_MAIN                           1151
#define IDC_TREE_PAGES                          1152
#define IDS_KEYWORD_AUDIO                       40000
#define IDS_KEYWORD_EXTENSION                   40001
#define IDS_KEYWORD_EXTRA                       40002
#define IDS_KEYWORD_EXTRA_UNSAFE                40003
#define IDS_KEYWORD_VERSION                     40004
#define IDS_KEYWORD_VIDEO                       40005
#define IDS_KEYWORD_EPISODE                     40006
#define IDS_KEYWORD_EPISODE_PREFIX              40007
