#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_MAIN                                101
#define IDD_ABOUT                               110
#define IDD_ANIME_INFO                          111
#define IDD_ANIME_INFO_PAGE01                   112
#define IDD_ANIME_INFO_PAGE02                   113
#define IDD_ANIME_LIST                          114
#define IDD_FEED_CONDITION                      115
#define IDD_FEED_FILTER                         116
#define IDD_FEED_FILTER_PAGE1                   117
#define IDD_FEED_FILTER_PAGE2                   118
#define IDD_FEED_FILTER_PAGE3                   119
#define IDD_FORMAT                              120
#define IDD_HISTORY                             121
#define IDD_INPUT                               122
#define IDD_MAIN                                123
#define IDD_SEARCH                              124
#define IDD_SEASON                              125
#define IDD_SETTINGS                            126
#define IDD_SETTINGS_ADVANCED                   127
#define IDD_SETTINGS_APP_GENERAL                128
#define IDD_SETTINGS_APP_LIST                   129
#define IDD_SETTINGS_LIBRARY_CACHE              130
#define IDD_SETTINGS_LIBRARY_FOLDERS            131
#define IDD_SETTINGS_RECOGNITION_GENERAL        132
#define IDD_SETTINGS_RECOGNITION_MEDIA          133
#define IDD_SETTINGS_RECOGNITION_STREAM         134
#define IDD_SETTINGS_SERVICES_HUMMINGBIRD       135
#define IDD_SETTINGS_SERVICES_MAIN              136
#define IDD_SETTINGS_SERVICES_MAL               137
#define IDD_SETTINGS_SHARING_HTTP               138
#define IDD_SETTINGS_SHARING_MIRC               139
#define IDD_SETTINGS_SHARING_SKYPE              140
#define IDD_SETTINGS_SHARING_TWITTER            141
#define IDD_SETTINGS_TORRENTS_DISCOVERY         142
#define IDD_SETTINGS_TORRENTS_DOWNLOADS         143
#define IDD_SETTINGS_TORRENTS_FILTERS           144
#define IDD_STATS                               145
#define IDD_TORRENT                             146
#define IDD_UPDATE                              147
#define IDD_UPDATE_NEW                          148
#define IDC_BUTTON_ADDFOLDER                    1000
#define IDC_BUTTON_BROWSE                       1001
#define IDC_BUTTON_CACHE_CLEAR                  1002
#define IDC_BUTTON_CANCELSEARCH                 1003
#define IDC_BUTTON_FORMAT_HTTP                  1004
#define IDC_BUTTON_FORMAT_MIRC                  1005
#define IDC_BUTTON_FORMAT_SKYPE                 1006
#define IDC_BUTTON_FORMAT_TWITTER               1007
#define IDC_BUTTON_MIRC_TEST                    1008
#define IDC_BUTTON_REMOVEFOLDER                 1009
#define IDC_BUTTON_TORRENT_BROWSE_APP           1010
#define IDC_BUTTON_TORRENT_BROWSE_FOLDER        1011
#define IDC_BUTTON_TWITTER_AUTH                 1012
#define IDC_CHECK_ANIME_ALT                     1013
#define IDC_CHECK_ANIME_REWATCH                 1014
#define IDC_CHECK_AUTOSTART                     1015
#define IDC_CHECK_CACHE1                        1016
#define IDC_CHECK_CACHE2                        1017
#define IDC_CHECK_CACHE3                        1018
#define IDC_CHECK_DETECT_MEDIA_PLAYER           1019
#define IDC_CHECK_DETECT_STREAMING_MEDIA        1020
#define IDC_CHECK_FOLDERS_WATCH                 1021
#define IDC_CHECK_GENERAL_CLOSE                 1022
#define IDC_CHECK_GENERAL_MINIMIZE              1023
#define IDC_CHECK_GOTO_NOTRECOGNIZED            1024
#define IDC_CHECK_GOTO_RECOGNIZED               1025
#define IDC_CHECK_HIGHLIGHT                     1026
#define IDC_CHECK_HIGHLIGHT_ONTOP               1027
#define IDC_CHECK_HTTP                          1028
#define IDC_CHECK_LIST_ENGLISH                  1029
#define IDC_CHECK_LIST_PROGRESS_AIRED           1030
#define IDC_CHECK_LIST_PROGRESS_AVAILABLE       1031
#define IDC_CHECK_MIRC                          1032
#define IDC_CHECK_MIRC_ACTION                   1033
#define IDC_CHECK_MIRC_MULTISERVER              1034
#define IDC_CHECK_NOTIFY_NOTRECOGNIZED          1035
#define IDC_CHECK_NOTIFY_RECOGNIZED             1036
#define IDC_CHECK_SKYPE                         1037
#define IDC_CHECK_START_CHECKEPS                1038
#define IDC_CHECK_START_LOGIN                   1039
#define IDC_CHECK_START_MINIMIZE                1040
#define IDC_CHECK_START_VERSION                 1041
#define IDC_CHECK_TORRENT_APP_OPEN              1042
#define IDC_CHECK_TORRENT_AUTOCHECK             1043
#define IDC_CHECK_TORRENT_AUTOCREATEFOLDER      1044
#define IDC_CHECK_TORRENT_AUTOSETFOLDER         1045
#define IDC_CHECK_TORRENT_AUTOUSEFOLDER         1046
#define IDC_CHECK_TORRENT_FILTER                1047
#define IDC_CHECK_TWITTER                       1048
#define IDC_CHECK_UPDATE_CHECKMP                1049
#define IDC_CHECK_UPDATE_CONFIRM                1050
#define IDC_CHECK_UPDATE_RANGE                  1051
#define IDC_CHECK_UPDATE_ROOT                   1052
#define IDC_CHECK_UPDATE_WAITMP                 1053
#define IDC_COMBO_ANIME_SCORE                   1054
#define IDC_COMBO_ANIME_STATUS                  1055
#define IDC_COMBO_DBLCLICK                      1056
#define IDC_COMBO_FEED_ELEMENT                  1057
#define IDC_COMBO_FEED_FILTER_ACTION            1058
#define IDC_COMBO_FEED_FILTER_MATCH             1059
#define IDC_COMBO_FEED_FILTER_OPTION            1060
#define IDC_COMBO_FEED_OPERATOR                 1061
#define IDC_COMBO_FEED_VALUE                    1062
#define IDC_COMBO_MDLCLICK                      1063
#define IDC_COMBO_SERVICE                       1064
#define IDC_COMBO_TORRENT_FOLDER                1065
#define IDC_COMBO_TORRENT_SEARCH                1066
#define IDC_COMBO_TORRENT_SOURCE                1067
#define IDC_COMBO_TORRENTS_QUEUE_SORTBY         1068
#define IDC_COMBO_TORRENTS_QUEUE_SORTORDER      1069
#define IDC_DATETIME_FINISH                     1070
#define IDC_DATETIME_START                      1071
#define IDC_EDIT_ANIME_ALT                      1072
#define IDC_EDIT_ANIME_FOLDER                   1073
#define IDC_EDIT_ANIME_PROGRESS                 1074
#define IDC_EDIT_ANIME_SYNOPSIS                 1075
#define IDC_EDIT_ANIME_TAGS                     1076
#define IDC_EDIT_ANIME_TITLE                    1077
#define IDC_EDIT_DELAY                          1078
#define IDC_EDIT_EXTERNALLINKS                  1079
#define IDC_EDIT_FEED_NAME                      1080
#define IDC_EDIT_HTTP_URL                       1081
#define IDC_EDIT_INPUT                          1082
#define IDC_EDIT_MIRC_CHANNELS                  1083
#define IDC_EDIT_MIRC_SERVICE                   1084
#define IDC_EDIT_PASS_HUMMINGBIRD               1085
#define IDC_EDIT_PASS_MAL                       1086
#define IDC_EDIT_PREVIEW                        1087
#define IDC_EDIT_SEARCH                         1088
#define IDC_EDIT_TORRENT_APP                    1089
#define IDC_EDIT_TORRENT_INTERVAL               1090
#define IDC_EDIT_USER_HUMMINGBIRD               1091
#define IDC_EDIT_USER_MAL                       1092
#define IDC_LINK_ACCOUNT_HUMMINGBIRD            1093
#define IDC_LINK_ACCOUNT_MAL                    1094
#define IDC_LINK_ANIME_FANSUB                   1095
#define IDC_LINK_DEFAULTS                       1096
#define IDC_LINK_NOWPLAYING                     1097
#define IDC_LINK_TWITTER                        1098
#define IDC_LIST_ADVANCED_SETTINGS              1099
#define IDC_LIST_EVENT                          1100
#define IDC_LIST_FEED_FILTER_ANIME              1101
#define IDC_LIST_FEED_FILTER_CONDITIONS         1102
#define IDC_LIST_FEED_FILTER_PRESETS            1103
#define IDC_LIST_FOLDERS_ROOT                   1104
#define IDC_LIST_MAIN                           1105
#define IDC_LIST_MEDIA                          1106
#define IDC_LIST_SEARCH                         1107
#define IDC_LIST_SEASON                         1108
#define IDC_LIST_STREAM_PROVIDER                1109
#define IDC_LIST_TORRENT                        1110
#define IDC_LIST_TORRENT_FILTER                 1111
#define IDC_PROGRESS_UPDATE                     1112
#define IDC_RADIO_MIRC_CHANNEL1                 1113
#define IDC_RADIO_MIRC_CHANNEL2                 1114
#define IDC_RADIO_MIRC_CHANNEL3                 1115
#define IDC_RADIO_TORRENT_APP1                  1116
#define IDC_RADIO_TORRENT_APP2                  1117
#define IDC_RADIO_TORRENT_NEW1                  1118
#define IDC_RADIO_TORRENT_NEW2                  1119
#define IDC_REBAR_MAIN                          1120
#define IDC_REBAR_SEASON                        1121
#define IDC_REBAR_TORRENT                       1122
#define IDC_RICHEDIT_ABOUT                      1123
#define IDC_RICHEDIT_FORMAT                     1124
#define IDC_RICHEDIT_UPDATE                     1125
#define IDC_SPIN_DELAY                          1126
#define IDC_SPIN_INPUT                          1127
#define IDC_SPIN_PROGRESS                       1128
#define IDC_SPIN_TORRENT_INTERVAL               1129
#define IDC_STATIC_ANIME_DETAILS                1130
#define IDC_STATIC_ANIME_IMG                    1131
#define IDC_STATIC_ANIME_STAT1                  1132
#define IDC_STATIC_ANIME_STAT2                  1133
#define IDC_STATIC_ANIME_STAT2_LABEL            1134
#define IDC_STATIC_ANIME_STAT3                  1135
#define IDC_STATIC_ANIME_STAT4                  1136
#define IDC_STATIC_APP_ICON                     1137
#define IDC_STATIC_CACHE1                       1138
#define IDC_STATIC_CACHE2                       1139
#define IDC_STATIC_CACHE3                       1140
#define IDC_STATIC_FEED_FILTER_DISCARDTYPE      1141
#define IDC_STATIC_FEED_FILTER_LIMIT            1142
#define IDC_STATIC_HEADER                       1143
#define IDC_STATIC_HEADER1                      1144
#define IDC_STATIC_HEADER2                      1145
#define IDC_STATIC_HEADER3                      1146
#define IDC_STATIC_HEADER4                      1147
#define IDC_STATIC_INPUTINFO                    1148
#define IDC_STATIC_TITLE                        1149
#define IDC_STATIC_UPDATE_DETAILS               1150
#define IDC_STATIC_UPDATE_PROGRESS              1151
#define IDC_STATIC_UPDATE_TITLE                 1152
#define IDC_STATUSBAR_MAIN                      1153
#define IDC_TAB_ANIME                           1154
#define IDC_TAB_MAIN                            1155
#define IDC_TAB_PAGES                           1156
#define IDC_TOOLBAR_FEED_FILTER                 1157
#define IDC_TOOLBAR_MAIN                        1158
#define IDC_TOOLBAR_MENU                        1159
#define IDC_TOOLBAR_SEARCH                      1160
#define IDC_TOOLBAR_SEASON                      1161
#define IDC_TOOLBAR_TORRENT                     1162
#define IDC_TREE_MAIN                           1163
#define IDC_TREE_SECTIONS                       1164
