query ($userName: String!) {
  MediaListCollection (userName: $userName, type: ANIME) {
    lists {
      entries {
        ...MediaListFragment
        media {
          ...MediaFragment
        }
      }
    }
  }
}
