query ($query: String, $season: MediaSeason, $seasonYear: Int, $format: MediaFormat, $status: MediaStatus, $page: Int) {
  Page(page: $page) {
    media(search: $query, season: $season, seasonYear: $seasonYear, format: $format, status: $status, type: ANIME, sort: START_DATE) {
      ...MediaFragment
    }
    pageInfo {
      total
      perPage
      currentPage
      lastPage
      hasNextPage
    }
  }
}
