fragment MediaFragment on Media {
  id
  title {
    romaji(stylised: true)
    english(stylised: true)
    native(stylised: true)
  }
  format
  status
  description
  startDate {
    year
    month
    day
  }
  endDate {
    year
    month
    day
  }
  episodes
  duration
  countryOfOrigin
  trailer {
    id
    site
  }
  updatedAt
  coverImage {
    extraLarge
  }
  genres
  synonyms
  averageScore
  popularity
  tags {
    name
    isMediaSpoiler
  }
  studios {
    edges {
      isMain
      node {
        name
      }
    }
  }
  nextAiringEpisode {
    airingAt
    episode
  }
}
