mutation (
    $id: Int,
    $mediaId: Int,
    $status: MediaListStatus,
    $scoreRaw: Int,
    $progress: Int,
    $repeat: Int,
    $notes: String,
    $startedAt: FuzzyDateInput,
    $completedAt: FuzzyDateInput) {
  SaveMediaListEntry (
      id: $id,
      mediaId: $mediaId,
      status: $status,
      scoreRaw: $scoreRaw,
      progress: $progress,
      repeat: $repeat,
      notes: $notes,
      startedAt: $startedAt,
      completedAt: $completedAt) {
    id
    status
    score(format: POINT_100)
    progress
    repeat
    private
    notes
    startedAt { year month day }
    completedAt { year month day }
    updatedAt
    media {
      id
      title {
        romaji(stylised: true)
        english(stylised: true)
        native(stylised: true)
      }
      format
      status
      description
      startDate { year month day }
      endDate { year month day }
      episodes
      duration
      countryOfOrigin
      trailer { id site }
      updatedAt
      coverImage { extraLarge }
      genres
      synonyms
      averageScore
      popularity
      tags { name isMediaSpoiler }
      studios { edges { isMain node { name } } }
      nextAiringEpisode { airingAt episode }
    }
  }
}
