name: Publish to Winget

on:
  release:
    types: [released]

jobs:
  publish:
    # Action can only be run on windows
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: erengy.Taiga
          token: ${{ secrets.WINGET_TOKEN }}
